config/routes.rb
Rails.application.routes.draw do
  resources :pages
  root 'pages#index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  # validates :avatar, attached: true, dimension: { width: { min: 800, max: 2400 } },
  # content_type: [:png, :jpg, :jpeg], size: { less_than: 100.kilobytes , message: 'is not given between size' }
  # validates :images, attached: true, limit: { min: 1, max: 3 }, content_type: [:png, :jpg, :jpeg, :mp3]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :pages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_page, only: %i[ show edit update destroy ]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
    @page = Page.new
  end

  def purge
    attachment = ActiveStorage::Page.find(params[:id])
    attachment.purge
    redirect_back fallback_location: root_path, notice: "success"
  end

  # GET /pages/1 or /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to root_path, notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.require(:page).permit(:home, :user_id, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DropboxClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/navbar' if current_user %>
    <%= yield %>
  </body>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

</html>

app/views/pages/_attach.html.erb
<p>
  <strong>Images:</strong>
  <% if @page.images.attached? %>
    <% @page.images.each do |attachment| %>
      <br>
      <% if attachment.image? %>
        <%= image_tag attachment, width: "200px" %>
      <% elsif attachment.audio? %>
        <audio controls>
          <source src="<%= rails_blob_url(attachment) %>" type="<%= attachment.content_type %>"/>
        </audio>
      <% elsif attachment.video? %>
        <video controls width="480">
          <source src="<%= rails_blob_url(attachment) %>" type="<%= attachment.content_type %>"/>
        </video>
      <% else %>
        <%= link_to attachment.filename, rails_blob_path(attachment, disposition: "attachment") %>
      <% end %>
      <br>
    <% end %>
  <% end %>
</p>

app/views/pages/_droper.html.erb
<div class="aziz">
  <%# <header>
    <i class="ion-briefcase"></i>
    <a>Try Dropbox Business</a>
    <a><i class="ion-ios-bell"></i></a>
    <i class="ion-gear-b"></i>
    <a>User Name</a>
  </header> %>
  <div class="wrapper">
    <main class="working-area">
      <%# <section class="folder-top">
        <div class="location">
          <i class="bi bi-folder-fill"></i>
          <h1>Location</h1>
          <h1>Folder Name</h1>
        </div>
        <div class="icon-menu">
          <i class="ion-document"></i>
          <i class="ion-folder"></i>
          <i class="ion-trash-a"></i>
          <input type="text" name="search" value="Search">
        </div>
      </section> %>
      <section class="files-container">
        <table><br>
          <tr class="file-labels">
            <button class="btn btn-primary btn-sm maga" data-bs-toggle="modal" href="#exampleModalToggle" role="button">Upload file</button>
            <%# <button class="btn btn-primary btn-sm maga" data-bs-toggle="modal" href="#exampleModalToggle" role="button">Create folder</button> %>
            <hr>
          </tr>
          <% @pages.each do |page| %>

          <% if page.user.id == current_user.id %>
            <% if page.images.attached? %>
              <% page.images.each do |picture| %>
                <tr class="folder">
                  <% if picture.image? %>
                    <td  style="font-size:12px;"><%= image_tag(picture, style: "width: 25px; height: 25px;") %> <%= link_to picture.filename, picture %></td>
                  <% elsif picture.filename.to_s.split('.').last === "pdf" %>
                    <td  style="font-size:12px;"><i class="bi bi-filetype-pdf" style="font-size:2em;"></i> <%= link_to picture.filename, picture %></td>
                  <% elsif picture.filename.to_s.split('.').last === "zip" %>
                  <td  style="font-size:12px;"><i  class="bi bi-file-earmark-zip" style="font-size:2em;"></i> <%= link_to picture.filename, picture %></td>
                  <% elsif picture.filename.to_s.split('.').last === "csv" %>
                  <td  style="font-size:12px;"><i  class="bi bi-filetype-csv" style="font-size:2em;"></i> <%= link_to picture.filename, picture %></td>
                   <% elsif picture.audio? %>
                  <td  style="font-size:12px;">
                  <i class="bi bi-file-earmark-music" style="font-size:2em;"></i>
                      <audio controls style="height: 20px;">
                    <source src=" <%= rails_blob_url(picture, disposition: "attachment") %>" type="audio/mpeg" style="length: 10px;"/>
                  </audio>
                  </td>
                  <% elsif picture.video? %>
                    <td  style="font-size:12px;">
                     <%= video_tag url_for(picture), controls: true, style:"width: 25px; height: 25px;" %> <%= link_to picture.filename, picture %>
                    </td>
                  <% else %>
                    <td  style="font-size:12px;"><i class="bi bi-folder" style="font-size:4em;"></i> <%= link_to picture.filename, picture %></td>
                  <% end %>
                  <td><%= link_to "Download",  rails_blob_path(picture, disposition: "attachment"), class: "btn btn-primary" %></td>
                  <td><%= button_to "Destroy", page, method: :delete, class: "btn btn-danger" %></td>
                </tr>
              <% end %>
            <% end %>
          <% end %>
          <% end %>
        </table>
      </section>
    </main>
  </div>
</div>
<%= render "form" %>
<script type='text/javascript'>
  window.onload = function() {
  $('.newChat-modal-toggle').on('click', function(e) {
    e.preventDefault();
    $('.newChat-modal').toggleClass('is-visible');
  });
  }
</script>

app/views/pages/_form.html.erb
<%= form_with(model: @page) do |form| %>
  <% if @page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% @page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

         
       <div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalToggleLabel">Upload File</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form.file_field :images, multiple: true, direct_upload: true %>
         <%= form.text_field :user_id, id: :pages_user_id, value: current_user.id, type: :hidden %>
      </div>
      <div class="modal-footer">
      <%= form.submit "Upload", class: " newChat-modal-create-btn" %>
      </div>
    </div>
  </div>
</div>

        
   
         
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", @page %> |
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/index.html.erb
<% if current_user %>
  <%= stylesheet_link_tag "pages"  %>
  <%= render 'droper' %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %>
  <%= link_to "Log in", new_user_sessions_path %>
<% end %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

  <p>
    <strong>Home:</strong>
    <%= @page.home %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @page.user_id %>
  </p>

<% @page.images.each do |picture| %>

<% if picture.image? %>
  <%= link_to image_tag(picture, class: "img_upload"), picture %>
  <% elsif picture.video? %>
   <%= link_to picture.filename, picture %>
  <% else %>
  <%= link_to picture.filename, picture %>
  <%= link_to "Download",  rails_blob_path(picture, disposition: "attachment")%>
<% end %>



<% end %>

<style>

.img_upload{
   border: 1px solid #ddd;
  border-radius: 4px;
  padding: 5px;
  width: 150px;
}

</style>

<div>
  <%= link_to "Edit this page", edit_page_path(@page) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>